### ISSUE TITLE
Silver Chest

### ISSUE THREAD

**Issue by Phoenix10King** [Dylan-Zheng/Rise-of-Kingdoms-Bot#11]
Please check it out, as bot dont opens silver chests at the tavern

**Comment by Dylan-Zheng** [comment]
bot will only open daily free silver chests.  which giving in blue 'Open' button

if you have free silver chest in tavern but not open in one round,  it should open in next round

**Comment by Phoenix10King** [comment]
i noticed when you have available free chest the time you opened the bot, will continue to open the chests ..
but if the bot is already in use wile daily reset happens, the bot will not open the new free chests

**Comment by Dylan-Zheng** [comment]
I don't if you are in this condition:

When new day is come(UTC), RoK will not update your tavern or daily objectives immediately (I don't know when they will update), but if you re-start you game it will immediately update your tavern and daily objectives.

so that bug may cause by this condition.

In next few update, I may put config parameter that will allow to restart game when UTC time 12 am
